services:
  watchdog-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/watchdog-agent:${TAG:-latest}
    container_name: watchdog-agent
    restart: unless-stopped
    ports:
      - "${WD_IP:-127.0.0.1}:${WD_REST_PORT:-9095}:9095"
      - "${WD_IP:-127.0.0.1}:${WD_PORT:-9090}:9090"
    networks:
      - teleremote-network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote-network:
    name: teleremote-network
    external: true
